### ISSUE TITLE
Cannot build targeting .NET 6.0 with 5.0 images.

### ISSUE THREAD

**Issue by me-2k** [sittzon/shinemonitor_api#8]
Thank you for your great work!

When trying to build from the latest commit I get this error 

`1.562 /usr/share/dotnet/sdk/5.0.408/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0. [/source/shinemonitor_api.csproj]`

I replaced dotnet 5.0 with 6.0 in the Dockerfile and building the image worked
```
diff --git a/Dockerfile b/Dockerfile
index b96f522..b33eca7 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,5 +1,5 @@
 # https://hub.docker.com/_/microsoft-dotnet
-FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
+FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
 WORKDIR /source
 
 # copy csproj and restore as distinct layers
@@ -11,7 +11,7 @@ COPY src/ ./
 RUN dotnet publish -c release -o /app --no-restore
 
 # final stage/image
-FROM mcr.microsoft.com/dotnet/aspnet:5.0
+FROM mcr.microsoft.com/dotnet/aspnet:6.0
 RUN apt-get update \
   && apt-get install -y python3 python3-pip \
   && pip3 install requests

```

**Comment by me-2k** [comment]
Se Pull Request https://github.com/sittzon/shinemonitor_api/pull/9

**Comment by sittzon** [comment]
Looks good! Will merge it
